### ISSUE TITLE
Output of GAM results in script 07_occurrence_indicators_modelling.Rmd overwritten 

### ISSUE THREAD

**Issue by soriadelva** [trias-project/indicators#133]
Example: https://github.com/trias-project/indicators/blob/65c55ab8ba82777507da19eef51ef1ad0284f820/src/07_occurrence_indicators_modelling.Rmd#L622
In this line the word output needs to be replaced by em_summary (and the same for the other paths in this code chunk).

**Comment by damianooldoni** [comment]
Thanks for finding this. Also, I will take care to read the files starting with `em_summary` in the 8th pipeline.
