### ISSUE TITLE
Indicator: number of new introductions of alien species per year in Belgium

### ISSUE THREAD

**Issue by timadriaens** [trias-project/indicators#17]
## Description
Temporal trends in first record rates of alien species (number of first records per year/per x year interval) for alien species (based on [Seebens et al. 2017](https://www.nature.com/articles/ncomms14435)). This indicator provides information on the number of new introductions in time, for instance the rate of increase of alien species introductions and the accumulation rate of alien species ([Rabitsch et al. 2016](https://www.sciencedirect.com/science/article/pii/S1617138115300339)). The information will be updated and refined as the checklist is further supplemented. 

## Data needs
- Country-level checklist
- Checklist-based
- Breakdowns: 
  - environment (marine, terrestrial, freshwater)
  - taxon (kingdom --> family)
  - native range
  - pathway (level 1 and level 2 CBD)
  - invasion stage (introduced, established)
  - source checklist
  - distribution (country-level: Belgium)

## Data output
The data retrieved by GBIF would be organized in a (tidy) data.frame

key | nubKey | scientificName | datasetKey | species | genus | family | order | class | phylum | kingdom | rank | speciesKey | taxonomicStatus | acceptedKey | accepted | locationId | locality | country | status | first_observed | last_observed | establishmentMeans | native range | origin | invasion stage | habitat | pathway_level1 | pathway_level2
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---

This data should be already filtered as explained in #21 .
This data output will serve as input for the plots based on group_by-like pipes, e.g. 
```r
df %>% 
  group_by(class) %>% 
  count()
```
It is suggested to write these series of `group_by()` in a function for plotting because of the high number of combinations of information.
See issue #18 about temporal information (`first_observed` and `last_observed`) in checklists.

**Comment by damianooldoni** [comment]
Yes, @peterdesmet for sure! Tomorrow I am "blocked" for preparing the hackathon. 
Among other things in the to-do-list there is also the "renaming" of some columns.

**Comment by damianooldoni** [comment]
Column names updated (and few others added) in "data output" table of https://github.com/trias-project/pipeline/issues/17#issue-308987170

**Comment by stijnvanhoey** [comment]
with respect to the requeste facet_subplots (aka Breakdowns). Not all are possible yet, we can trakc the progress here:

* [ ] environment (marine, terrestrial, freshwater) -> not in data available
* [x] taxon (kingdom --> family)
* [ ] native range  -> this is new in a property-value way in the input data set, we should revisit this to make sure no pivoting is required for this operation
* [x] pathway (level 1 )
* [ ] pathway (level 2 CBD) -> actually this should be the pathway indicator #27 
* [x] distribution (country-level: Belgium) -> `locality column`

With respect to `invasion stage` (introduced, established) @timadriaens did request an additional line option:
* [ ] `establishdmeans`-based? ->  data on established is not available

For the source checklist, a line based breakdown was requested by @timadriaens ; is this of any value?
* [ ] source checklist?

**Comment by stijnvanhoey** [comment]
Similar to #20 , the facet graphs underneath are included as well as part of the functionality; e.g. for `kingdom`:
![image](https://user-images.githubusercontent.com/754862/38874211-db22bc80-4257-11e8-8a75-062e89142940.png)
@Yasmine-Verzelen you can further check the consequences of different smoothers.

**Comment by damianooldoni** [comment]
@Yasmine-Verzelen and @SanderDevisscher: my workflow .Rmd has passed internal reviews and it is now merged in master. 
Please, pull from origin to have an updated branch via the following git line:
```
git pull origin master
```
Unfortunately you cannot do this via GitHub Desktop. So, the most important stuff is the fact that the database is now 100% tidy! That means that you are now able to make facet_subplots for native range breakdown as well :+1:. You can start by importing the new version of file `test_data_output_checklist_indicators.tsv`. By pulling the master in your branch you get this file updated as well.
I have consequently updated the column names of the table at the very beginning of this issue https://github.com/trias-project/pipeline/issues/17#issue-308987170.
Let me know for anything!

**Comment by timadriaens** [comment]
Hi, where do I find the latest graphs based on the unified checklist including all the breakdowns, need them for a chapter in the Living Planet Report Belgium @damianooldoni ?

**Comment by damianooldoni** [comment]
@timadriaens : I will rerun the checklist indicators pipelines and push to master: as written via Hangout I plan it to do on June 24th (25th as backup if unexpected errors occur).

**Comment by damianooldoni** [comment]
By the way, this issue should be closed as this indicator is now working and it is updated on master.
