### ISSUE TITLE
Common species to test for AOO

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/indicators#39]
@damianooldoni FYI:

Species | taxon_key | records in BE | type
--- | --- | --- | ---
Pieris rapae | 1920496 | 175197 | butterfly
Pararge aegeria | 8049830 | 145023 | butterfly
Vanessa atalanta | 1898286 | 153714 | butterfly
Aglais io | 4535827 | 130204 | butterfly
Anas platyrhynchos | 9761484 | 101445 | bird
Rutilus rutilus | 2359706 | 90766 | fish
Cirsium arvense | 3113414 | 40449 | plant

**Comment by damianooldoni** [comment]
I leave this issue open just as a nice recap table for a while.

**Comment by damianooldoni** [comment]
This issue can be closed in this repo. Moved to https://github.com/trias-project/aoo-paper/issues/1.
