### ISSUE TITLE
Physella acuta does not have Haitia acuta as synonym

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/indicators#4]
_Originally reported in https://github.com/trias-project/alien-macroinvertebrates/issues/25_

`Physella acuta` is a species in the **Alien macroinvertebrates** checklist (`alien-macroinvertebrates-checklist:taxon:57`). `Haitia acuta` should be a synonym of it... and thus find occurrence records named as such (including 167 occurrences in the Alien macroinvertebrates occurrence dataset, e.g. `PB:Ugent:AqE:2342`). The GBIF backbone however considers both 2 accepted species:

* [Physella acuta (Draparnaud, 1805)](https://www.gbif.org/species/5189806)
* [Haitia acuta Draparnaud, 1805](https://www.gbif.org/species/7790194)

Physella acuta thus won't return records for Haitia acuta.

Note: Haitia acuta is the only species in the macroinvertebrate occurrence dataset that is not listed by the same name in the checklist.

**Comment by peterdesmet** [comment]
In fact, no synonyms are listed for [Physella acuta (Draparnaud, 1805)](https://www.gbif.org/species/5189806), while lots are listed for [Haitia acuta](https://www.gbif.org/species/7790194) (but not `Physella acuta`)

**Comment by peterdesmet** [comment]
@timadriaens pinging you here.

**Comment by timadriaens** [comment]
in case of doubt, I refer to [worms](http://www.marinespecies.org/aphia.php?p=taxdetails&id=234093), according to them the correct name is [Physa acuta](http://www.marinespecies.org/aphia.php?p=taxdetails&id=819960#vernaculars)

**Comment by peterdesmet** [comment]
Ok, so very different in Worms vs GBIF. GBIF considers [Physa acuta](https://www.gbif.org/species/8711883) as a synonym of Paraplexa cornea.

**Comment by peterdesmet** [comment]
Unfortunately, Worms doesn't provide info on `Haitia acuta`.

**Comment by damianooldoni** [comment]
Good news: [Haitia acuta Draparnaud, 1805](https://www.gbif.org/species/7790194) is a synonym of [Physella acuta (Draparnaud, 1805)](https://www.gbif.org/species/5189806) on GBIF. So, this taxonomic problem has been solved.
