### ISSUE TITLE
Discuss common data cleaning pipeline

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/indicators#41]
It seems WP3 and WP4 both need to clean GBIF occurrence data. 
We should : 
1. Discuss a common data filtering strategy.
2. Create a pipeline dedicated to data cleaning

**Comment by peterdesmet** [comment]
by @amyjsdavis: I originally envisioned the modeling framework building on code already developed by you and others on the TrIAS team, but being an entirely separate process beginning with the data download since I require global data and I also require more stringent filtering than what is needed for the development of the indicators. However, I understand yours and Peter's desire to not overwhelm the GBIF platform and to develop a data cleaning pipeline. I see this as the only potential area of overlap between our work packages.

If you want, we can get together to discuss this early next year, or just work on it remotely. 

To give you an idea of my requirements, here is the R code I am currently using to filter my data.

```R
#Clean global occurrence data (occ)

library(rgbif)
library(tidyverse)

occ_clean<- occ %>%
   filter(basisOfRecord!="FOSSIL_SPECIMEN") %>%
   filter(hasCoordinate =="TRUE") %>%
   filter(hasGeospatialIssues=="FALSE") %>%
   filter(is.na(coordinateUncertaintyInMeters)| coordinateUncertaintyInMeters< 708) %>%
   select(taxonKey,species, scientificName,decimalLatitude,decimalLongitude,eventDate,year,coordinateUncertaintyInMeters,datasetKey,countryCode,establishmentMeans)%>%#select desirable variables
   filter(!grepl("^[0-9]+(\\.[0-9]{0,1})?$",decimalLatitude))%>%
   filter(!grepl("^[0-9]+(\\.[0-9]{0,1})?$",decimalLongitude)) #filter points with unacceptable accuracy
```

**Comment by amyjsdavis** [comment]
Let's meet on the 15th of January at 13h:00. Room details to follow.

**Comment by damianooldoni** [comment]
1. Data cleaning filters used both for indicators and risk assessment can be passed immediately to GBIF for triggering a (smaller) download.
2. The filters which are not used by both , would be implemented in two separate data cleaning pipelines in a second step.

Here below I try to summarize which properties are common and which are not:

## country

The field `countryCode` is not a common field. 
For indicators: `countryCode = "BE"`, while risk assessment works at global level

## basisOfRecord
`basisOfRecord`: one of `HUMAN_OBSERVATION` and `PRESERVED_SPECIMEN`. This field is common. @amyjsdavis and @DiederikStrubbe : removing only fossils is dangerous. Including machine observations ends up with highly overestimating the presence of some species in particular areas. See here complete list of terms: https://rs.gbif.org/vocabulary/dwc/basis_of_record.xml.

## occurrenceStatus

`occurrenceStatus` is a common field. We have to exclude both `absent` and `excluded` (subclass of `absent`). @amyjsdavis , @DiederikStrubbe : unless you use these ones for modelling real absences? But I don't think they are correct and completely useful. In any case, they are surely not complete: only extensive detailed campaign (a minority of GBIF data) end up with presences AND absences. 

## year

`year` has to be present: common filter. We work at `year` level, so this field is the only one which is really important.

## coordinates

`decimalLatitude` and `decimalLongitude` both present: common. We both need them: indicators -> occupancy; risk assessment -> climate data.

## coordinate uncertainty

`coordinateUncertaintyInMeters` has to be NA or less than 700m. @amyjsdavis , @DiederikStrubbe : as discussed together in January, this is risky. `coordinateUncertaintyInMeters` = Not Available is not syononym of very precise data! Moreover, removing data with uncertainty higher than 700m means removing a significant part of data. I think we agreed with assigning a default 1000m uncertainty to these data. and then randomly assigning the pts based on their uncertainty (how to do it will be discussed in a new issue).

I think tommorrow during TrIAS core meeting we can get a final decision about it. Do not hesitate to write comments below if needed.

**Comment by damianooldoni** [comment]
Done in pipelines [src/download.Rmd](https://github.com/trias-project/occ-processing/blob/master/src/belgium/download.Rmd) and [src/create_db.Rmd](https://github.com/trias-project/occ-processing/blob/master/src/belgium/create_db.Rmd) of repo `occ-processing`.
Issue can be closed.
