### ISSUE TITLE
Is there need to use a European reference grid at 1x1km resolution?

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/indicators#45]
Based on previous conversations, we found that no worldwide grid is available and it is actually not needed for risk assessment (RA). We need it at European level for RA and at Belgian level for indicators. Based on what I can find from [European Environmental Agency page](https://www.eea.europa.eu/data-and-maps/data/eea-reference-grids-2) I cannot find any grid at 1x1km resolution at European level, only 10x10km and 100x100km.

@DiederikStrubbe, @amyjsdavis : do you need to calculate occupancy at European level at 1x1km or is it fine for you to get 1x1km resolution at Belgian level?

If you really need, do you have ideas how to get it? Maybe we can build it by using all reference grids at country level and join them together but we will have a lot of problems at country borders where duplicates will occur. Something to think about... Let me know. If you have a shape file for it, could you please upload it in `./data/external/`? Thanks.

**Comment by damianooldoni** [comment]
After our TrIAS core meeting we know that:
1. we work at European level for risk assessment, so data and grid covering all Europe are needed.
2. do we need to work at 1x1km level or is it for you enough the grid at 10x10km? If 1x1km grid, then we have to get it somehow. @amyjsdavis: do you have it? And from who? Can be found on internet? Is it an "official" grid? I couldn't find it on [EAA ineternetsite](https://www.eea.europa.eu/data-and-maps/data/eea-reference-grids-2) (only reference grids at 10x10km and 100x100km). We can make it ourselves in a documented, open and repeatable way (TrIAS style...) by stitching the country reference grids together. Just let us know. If you find that working at 10x10km scale is enough, then we use the reference grid already provided by EAA.

**Comment by amyjsdavis** [comment]
@damianooldoni : Yes I have a grid. I have to add Norway to it. I will send it to you when it is ready.

**Comment by peterdesmet** [comment]
Hi @amyjsdavis as discussed on phone, once your finished sending the grid to KMI, can you:

1. Include the link to the 1km grid (without Norway) in this issue
2. Add the code for adding Norway to the grid in this repo: https://github.com/trias-project/eaa-reference-grid-1km

No need to send us the file.

**Comment by amyjsdavis** [comment]
https://www.eea.europa.eu/data-and-maps/data/reference-grid-for-land-cover-accounts-leac/zipped-shape-file-eea-reference-grid-1k-vector-data-polygon-leac-coverage/zipped-shape-file-eea-reference

**Comment by peterdesmet** [comment]
Great, thanks! I noticed this grid only covers land. Does that mean that marine species will be ignored in the analyses?

**Comment by amyjsdavis** [comment]
They will require a different framework and different set of data (e.g see http://www.bio-oracle.org/ and http://www.emodnet.eu/, 
We will tackle this after we model the terrestrial and aquatic (non-marine) species.
