### ISSUE TITLE
Compensating research effort bias for occupancy: temporal solution vs spatial solution?

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/indicators#46]
The goal of this issue is to discuss the best way of compensate the research effort bias. Based on interesting discussions with @qgroom and @timadriaens, I am working on two different ideas:
## Temporal solution 
This issue starts from point 4 of @qgroom' [comment on issue 40](https://github.com/trias-project/pipeline/issues/40#issuecomment-443216705): 
> Occupancy values are clearly sensitive to research effort. To improve it we need to aggregate along years. The (lack of) research effort is also a source of underestimation of occupancy: some areas are scanned at a certain year, others in other years. So, the question is: how many years should we use to get the optimal aggregation span? To do it, we should plot occupancy vs number of aggregation years (aggregation span). Hopefully we get the same curve as the curve of occurrence vs research effort (search literature for references). We should see a kind of saturation point. Do it species by species (year by year): the saturation point will be probably different among taxa. That would be obviously a problem as we aim to hold it simple, i.e. using a single aggregation span. Of course, we will have to make a decision at the end (number of years to use for temporal aggregation should not be too high, otherwise we loose policy relevancy), but investigation is needed.

I am investigating the research effort bias correction on branch `research_effort_bias_corrction`, more specifically in [`./src/_research_effort_bias.Rmd`](https://github.com/trias-project/pipeline/blob/research_effort_bias_corrction/src/_research_effort_bias.Rmd).

Here below some plots showing the occupancy vs. time window from 2007 to 2018. I don't see a clear saturation curve valid for all species and all years. I think correcting research effort bias by working on temporal dimension will be not effective as we want to use temporal dimension to detect changes in occupancy as well. 
![2014research_effort_bias_time_window](https://user-images.githubusercontent.com/33662631/52649042-d527f700-2ee7-11e9-812a-7b8dac6639c0.png)
![2015research_effort_bias_time_window](https://user-images.githubusercontent.com/33662631/52649043-d527f700-2ee7-11e9-9d8c-b67939451df6.png)
![2016research_effort_bias_time_window](https://user-images.githubusercontent.com/33662631/52649044-d5c08d80-2ee7-11e9-9c4d-148e77bb8534.png)
![2017research_effort_bias_time_window](https://user-images.githubusercontent.com/33662631/52649046-d5c08d80-2ee7-11e9-8701-062972484dc3.png)
![2018research_effort_bias_time_window](https://user-images.githubusercontent.com/33662631/52649049-d5c08d80-2ee7-11e9-9985-17c35bd83325.png)
![2007research_effort_bias_time_window](https://user-images.githubusercontent.com/33662631/52649050-d6592400-2ee7-11e9-8198-34c7df9cb338.png)
![2008research_effort_bias_time_window](https://user-images.githubusercontent.com/33662631/52649051-d6592400-2ee7-11e9-8916-0fc8bcf5ddf6.png)
![2009research_effort_bias_time_window](https://user-images.githubusercontent.com/33662631/52649052-d6592400-2ee7-11e9-92f8-432a45b47a17.png)
![2010research_effort_bias_time_window](https://user-images.githubusercontent.com/33662631/52649053-d6592400-2ee7-11e9-86cb-52e3a82fe4a7.png)
![2011research_effort_bias_time_window](https://user-images.githubusercontent.com/33662631/52649054-d6f1ba80-2ee7-11e9-95b0-60763ede4b62.png)
![2012research_effort_bias_time_window](https://user-images.githubusercontent.com/33662631/52649055-d6f1ba80-2ee7-11e9-9dcb-c541916186fb.png)
![2013research_effort_bias_time_window](https://user-images.githubusercontent.com/33662631/52649056-d78a5100-2ee7-11e9-9cd9-bee3c6ac9029.png)

## Spatial solution
As alternative, @timadriaens and I discussed yesterday a possible alternative: why not working on spatial scale? We can calculate yearly occupancy dividing #occupied cells at species level by #occupied cells at kingdom level instead of dividing by #cells of Belgium. This way we will remove all cells not showing any research effort at all. I am still working on making this calculation feasible (technical discussion opened in #47).
Meanwhile, ideas and comments about temporal and/or spatial solution are welcome!

**Comment by qgroom** [comment]
Yes, I am sure I've seen this done before. One minor problem is because you
include the numerator in the denominator the baseline might not be as
stable as you think. Perhaps we should look at Frescalo by Hill, though I
have never liked the approach, because of the assumptions it makes.
I'm on the plane at the moment, but will look at the saturation curves when
I get to the ground.
Quentin

**Comment by damianooldoni** [comment]
We don't lump data on temporal axis. I close the issue.
