### ISSUE TITLE
How retrieve number of occupied cells at specific rank level

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/indicators#47]
Based on discussion in #46 , we would like to know how many of our cells are occupied at a certain rank level (in our case, we thought about kingdom, but the issue can be extended easily to any other rank). As we are working at 1km scale (~50k cells) and we are working on a time span of around 50 years, let's say, this means sending a lot of queries to GBIF, which is not recommended (see interesting discussion about here: https://github.com/ropensci/rgbif/issues/320).
So, how to get this aggregated(!) numbers in a quite fast way and without sending thousands of queries?
If I see how fast the GBIF tool [observation trend](https://www.gbif.org/tools/observation-trends/about) works, I think a possible solution is in the air. 
This is the link to the repo behind the tool: https://github.com/gbif/species-population.

Moreover, GBIF has already an API for doing it, they are writing the documentation for it: see https://github.com/gbif/species-population/issues/6. However, the issue is quite old, their plans are very likely changed.

Analyzing the requests my computer does while searching for `Branta canadensis` against higher taxon `Anatidae`, I see some requests which are linked to binary files with `.mvt` extension:

https://api.gbif.org/v2/map/occurrence/regression/3/3/2.mvt?higherTaxonKey=2986&minYears=10&taxonKey=5232437&year=1970,2015

and if we zoom a lot:

https://api.gbif.org/v2/map/occurrence/density/7/65/42.mvt?srs=EPSG:3857&basisOfRecord=OBSERVATION&basisOfRecord=HUMAN_OBSERVATION&basisOfRecord=MACHINE_OBSERVATION&basisOfRecord=MATERIAL_SAMPLE&basisOfRecord=PRESERVED_SPECIMEN&higherTaxonKey=2986&minYears=10&taxonKey=5232437&year=1970,2015

Notice the `/v2` instead of `/v1`, the [GBIF API standard version](http://api.gbif.org/v1/). So, the tool loads some binary files (downloadable, just click on the links) and query on them. The directory structure is very likely linked to zoom level and geographical area. I have tried to opened one of these files in R via `ReadBin()` but it didn't work. I am afraid I need to know the file structure before hand.

Another way: in the issue cited before (https://github.com/ropensci/rgbif/issues/320) Tim Robertson was speaking about SQL API which is under development: is it the right alternative to get what we want?

@stijnvanhoey, @peterdesmet : what do you think we can implement and what's at GBIF side? Thanks!

**Comment by stijnvanhoey** [comment]
I do think the required information about setting up the query is available in the [API docs](https://www.gbif.org/developer/maps) using the `.mvt` as `format` option to the query resulting in mapbox vector tiles:

> Vector tiles use Mapbox Vector Tile format, and contain a single layer occurrence. Objects in that layer are either points (default) or polygons (if chosen), each object has a total value; that is the number of occurrences at that point or in the polygon.

In Python, I know of a [decoder](https://github.com/tilezen/mapbox-vector-tile) for these files, e.g. for the result of your regression query:

```
import mapbox_vector_tile
with open('2.mvt', 'rb') as f:
    data = f.read()
decoded_data = mapbox_vector_tile.decode(data)
decoded_data
```
resulting in:

```
{'regression': {'extent': 4096,
  'features': [{'geometry': {'coordinates': [[[4627, 3091],
       [4589, 3026],
       [4513, 3026],
       [4475, 3091],
       [4513, 3157],
       [4589, 3157],
       [4627, 3091]]],
     'type': 'Polygon'},
    'id': 0,
    'properties': {'SSE': 0.14110256225160012,
     'groupCounts': '{"1972":1,"1977":6,"1978":27,"1979":40,"1982":23,"1983":40,"1984":145,"1985":8,"1987":27,"1988":2,"1989":10,"1990":1,"1991":10,"1992":8,"1994":4,"1999":1,"2000":25,"2001":46,"2002":5,"2003":48,"2004":19,"2005":79,"2006":28,"2007":28,"2008":35,"2009":89,"2010":167,"2011":348,"2012":361,"2013":424,"2014":188,"2015":199}',
     'id': '16915.0:9197.0',
     'intercept': 0.4211443769527274,
     'interceptStdErr': 1.9541723886627564,
     'meanSquareError': 0.004703418741720004,
     'significance': 0.840226171719543,
     'slope': -0.00019903926827075224,
     'slopeStdErr': 0.0009787496164624394,
     'speciesCounts': '{"1984":2,"1989":3,"1994":1,"2004":1,"2006":1,"2007":1,"2008":1,"2010":3,"2011":1,"2013":3,"2014":2,"2015":1}'},
    'type': 3},
   {'geometry': 
... # and so on for each geometry in the response, i.e. each hexagon in this case
```

__Note__: this regression query is probably very useful for you as it provides number of occurrences for each year and indeed not described in the API docs where only the `density` and `ad-hoc` call are described.

So, decoding of the `mvt` files is certainly possible, but I'm wondering how to spatially link your rectangular grid with the [options](https://api.gbif.org/v2/map/debug/ol/#) the vector tiles can provide to you?

**Comment by damianooldoni** [comment]
Thanks @stijnvanhoey! I will further read about it.

**Comment by damianooldoni** [comment]
It seems it is still not possible. 
Meanwhile we worked in the direction of producing a Belgian data cube (see repository [trias-project/occ-processing](https://github.com/trias-project/occ-processing)): we produced a baseline data cube at kingdom level. If in future we decide to use baselines at another taxonomic rank, the same workflow can be applied.
This issue is therefore solved.
