### ISSUE TITLE
Data publishing delay assessment

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/indicators#48]
The assessment of data publishing delay is very important for a correct use of segmented regression or any other analysis for studying the emerging status of alien species. If we see a sensible decrease in data publication, then we can assume that the decrease in number of occurrences at species level is not realistic. A easy but effective way to find it, is to get number of occurrences with geographic coordinates in Belgium for each kingdom during the last years. 

You can manually search via GBIF site if you want. Here below a link to get all occurrences for: 
1. `year = 2017`
2. `kingdom = Animalia`
3. `hasCoordinate=TRUE`
4. `country=BE`
https://www.gbif.org/occurrence/search?has_coordinate=true&year=2017&kingdom_key=1&country=BE

Here below the graphs. You can make them on your laptop, by using the code in [this gist](https://gist.github.com/damianooldoni/17a6a29fdc6ef40d4f97e8f618a71bb6).

![n_occ_animalia](https://user-images.githubusercontent.com/33662631/52960791-d0f15300-3399-11e9-9380-2bf6c4e82000.png)
![n_occ_bacteria](https://user-images.githubusercontent.com/33662631/52960792-d0f15300-3399-11e9-9f17-2cd78ff7de5a.png)
![n_occ_chromista](https://user-images.githubusercontent.com/33662631/52960793-d189e980-3399-11e9-9164-82ca1cbdd521.png)
![n_occ_fungi](https://user-images.githubusercontent.com/33662631/52960794-d189e980-3399-11e9-96f9-13142d13cac7.png)
![n_occ_incertae sedis](https://user-images.githubusercontent.com/33662631/52960796-d189e980-3399-11e9-85bb-36540e238d5b.png)
![n_occ_plantae](https://user-images.githubusercontent.com/33662631/52960798-d189e980-3399-11e9-81d3-03add5247f47.png)
![n_occ_protozoa](https://user-images.githubusercontent.com/33662631/52960799-d2228000-3399-11e9-8eac-31a70e11ff7e.png)
![n_occ_viruses](https://user-images.githubusercontent.com/33662631/52960800-d2228000-3399-11e9-86b0-7845a5207a2d.png)
You can see that two years is a good threshold for publishing delay. Only Fungi do better in Belgium. With the popularity of Citizen Science projects like iNaturalist this delay will eventually decrease in the future. But, at the moment 2016 seems the last year to use for performing segmented regression. At the end of 2019, we could then include 2017.

@qgroom , @timadriaens , @ToonVanDaele , what do you think about?

**Comment by qgroom** [comment]
Like all these thing, there is a long tail of unavailable records. The Garden'd data is a good example. Is it possible to always show all the points in the output, but restrict the segmented regresion to exclude the last two years? That way, if something different is happening in recent years it is not completely missed.

**Comment by damianooldoni** [comment]
Good point. The occurrence data we start with are never deleted so it will be not a problem to show very last years in graphs.

**Comment by damianooldoni** [comment]
@timadriaens , @ToonVanDaele : what do you think? Do we take 2 years delay from present year? I don't see any other option.

**Comment by timadriaens** [comment]
yes I think the last 2 years is fine
