### ISSUE TITLE
basic data to display in Harmonia

### ISSUE THREAD

**Issue by timadriaens** [trias-project/indicators#53]
It would be nice to have some very basic data in Harmonia on which the more advanced indicators/indexes are based. This always helps interpreting trend graphs. The ones I can think of are:

- the number of occurrences per year 
- the number of km squares per year

I believe for now these are 'byproducts' of the pipeline, perhaps we should think of a suitable output (simple barplot graph).

**Comment by damianooldoni** [comment]
I agree. My workflow would be to save these data so that they can be easily used by displaying it in Harmonia. We can obviously decide the style of the graphs so that Harmonia maintainers have some guidelines while developing their webservices.

**Comment by damianooldoni** [comment]
I think we agreed about this and so we'll do. No more updates are needed about this. Issue closed.
