### ISSUE TITLE
Correctness shapefile Belgian regions coming from our server

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/indicators#59]
As noticed while commenting #57 , we can download shapefiles of Belgian regions from this federal site: https://data.gov.be/en/dataset/fb1e2993-2020-428c-9188-eb5f75e284b9

I have just compared the shapefiles from our server, as uploaded by @timadriaens, with the downloaded ones, via R.

I see the following:

1. the shapefiles of Belgian regions coming from INBO server appear shifted if we compare it with the national Belgian borders (by openStreetMap). See figure below: 
![image](https://user-images.githubusercontent.com/33662631/61446165-0ac98400-a94f-11e9-95cd-533b4b6079f8.png)
2. the shapefiles of Belgian regions downloaded by internetsite of Federal Government are not shifted. See figure below: 
![image](https://user-images.githubusercontent.com/33662631/61446350-41070380-a94f-11e9-8617-836d131a3db9.png)

I transofrmed both shapefiles to WGS84 before plotting them with `mapview`/`leaflet` of course.

@timadriaens , can you please check it via a GiS software?

**Comment by damianooldoni** [comment]
Just for more information, I set here the code to reproduce this strange behavior for further inspection:

```r
library(sf)           # Spatial functions
library(leaflet)      # Map visualizations
library(tidyverse)    # Data science
library(here)         # To work with paths

## Belgian regions as obtained from our server

belgian_regions <- st_read(here("data", "external", "Regions_Belgium"))
crs_belgian_regions <- st_crs(belgian_regions)
crs_belgian_regions

## Belgian regions as obtained from
## https://data.gov.be/en/dataset/fb1e2993-2020-428c-9188-eb5f75e284b9

layers <- st_layers(here("data", "external", "belgium_shapefile_20190701"))
layers

belgian_regions_gov <- st_read(here("data", "external", "belgium_shapefile_20190701"), 
                               layer = "AD_5_Region")
crs_belgian_regions_gov <- st_crs(belgian_regions_gov)
crs_belgian_regions_gov

## Compare two maps

# Compare CRS

crs_belgian_regions_gov == crs_belgian_regions

# Compare region's area in square meters

regions_area <- st_area(belgian_regions)
names(regions_area) <- belgian_regions$Naam
regions_area <- sort(regions_area)
regions_area
head(regions_area)

regions_area_gov <- st_area(belgian_regions_gov)
names(regions_area_gov) <- belgian_regions_gov$NameDut
regions_area_gov <- sort(regions_area_gov)
regions_area_gov

diff_regions_area <- regions_area_gov - regions_area
diff_regions_area

# Compare total areas (= all Belgium) in square meters
total_area <- as.numeric(sum(st_area(belgian_regions)))
total_area

total_area_gov <- as.numeric(sum(st_area(belgian_regions_gov)))
total_area_gov

diff_total_area <- total_area_gov - total_area
diff_total_area

## Transform both maps to wgs_84

wgs_84 <- st_crs("+init=epsg:4326")
belgian_regions <- st_transform(belgian_regions, wgs_84)
belgian_regions_gov <- st_transform(belgian_regions_gov, wgs_84)

## Leaflet

map_belgian_regions <- 
  leaflet() %>%
  addTiles() %>%
  addPolygons(data = belgian_regions,
              weight = 1, opacity = 0.5, fillOpacity = 0.1, color = "blue")


l <- 
  leaflet() %>%
  addTiles()
mapview::mapview(list(belgian_regions_gov, belgian_regions), map =l)
```

**Comment by carinewils** [comment]
Damiano,
Which file did you use from the open data portal? There are two: one in
Lambert2008 (EPSG:3812) and one in Lambert72 (EPSG:31370).
The transformation to WGS84 is different for both projections: Lambert72
has a different datum and uses a different ellipsoïd than Lambert2008.
My guess is that you need to specify the SRID of the initial shapefile used
in the transformation, especially for Lambert72 so the correct
transformation parameters are used.
Carine

**Comment by damianooldoni** [comment]
We don't use anymore any layer from INBO servers. Only EAA grids used.
