### ISSUE TITLE
natural_dispersal: pathway level1 and level2 not correct

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/indicators#61]
I used the first underscore (`_`) to distinguish pathway level 1 and pathway level 2 (see [pathway table](https://github.com/trias-project/vocab/blob/master/vocabulary/pathway/pathways.tsv)). This is good for all possibilities except `natural_dispersal`, which is a pathway level1, and should be not divided in two levels.
Thanks to @SanderDevisscher to find this bug. I try to solve it now.

**Comment by damianooldoni** [comment]
Bug solved: output file `data_input_checklist_indicators.tsv` is updated.
Internet site is not updated. Travis CI was taking too much time to make a new version and any attempt was aborted. Still, data are ok now.

**Comment by damianooldoni** [comment]
@SanderDevisscher : can this be closed? I think so.

**Comment by SanderDevisscher** [comment]
@damianooldoni Yes

**Comment by damianooldoni** [comment]
Based on a by scheme provided @timadriaens, I find that `natural_dispersal` is a pathway level 2, the only one belonging to pathway level 1 `unaided`. I modify the mapping now.

Another little doubt: I see in unified taxa with pathway `cbd_2014_pathway:unaided` and other taxa with pathway `cbd_2014_pathway:natural_dispersal`. So, I will map `cbd_2014_pathway:unaided` by assigning value `unknown` to level 2:

pathway original (from description extension) | pathway_level1 | pathway_level2
---  | --- | ---
cbd_2014_pathway:unaided | unaided | unknown
cbd_2014_pathway:natural_dispersal | unaided | natural_dispersal

@timadriaens , @SanderDevisscher , are you ok with this?

**Comment by timadriaens** [comment]
This kind of question is of course easier to answer if I had a few species as an example. But indeed, unaided = spontaneous dispersal from other areas where the species was introduced. So it is the same as natural dispersal. In other words: yes, very much ok @damianooldoni, thx for spotting this (it is an important pathway for the Union List species).

**Comment by damianooldoni** [comment]
Thanks @timadriaens. I wrote issues in each checklist where this occurred.

Actually there are two problems in one:
- `cbd_2014_pathway:natural_dispersal` is wrong, it should be `cbd_2014_pathway:unaided_natural_dispersal`: see issue in RINSE pathway

- `cbd_2014_pathway:unaided` is correct but based on your comment could be improved to `cbd_2014_pathway:unaided_natural_dispersal` (otherwise we have no info at level 2)

Meanwhile I write a patch in the preprocessing of unified data for checklist indicators and I map both `cbd_2014_pathway:unaided` and `cbd_2014_pathway:natural_dispersal` to `cbd_2014_pathway:unaided_natural_dispersal`.

**Comment by timadriaens** [comment]
perfect
