### ISSUE TITLE
species on checklist without occurrences

### ISSUE THREAD

**Issue by timadriaens** [trias-project/indicators#66]
New species on one of the checklists without any occurrences should actually appear in the list as "appearing". An example is the recently discovered _Procambarus acutus_  which was meanwhile added to the macroinvertebrates checklist, but does not appear yet in any of our datasets on gbif (pending publication of the records...). Is it possible to retreive those in the indicator pipeline @damianooldoni e.g. for the separate list of appearing spp?

**Comment by damianooldoni** [comment]
Yes, we can get it quite easily, but be prepared to screen a list of ~600 taxa or more!
With the last generated datacube we have ~1900 alien species linked to (at least one) occurrences, i.e. 300 more than previous datacube. However, hundreds of taxa are still without occurrences.

**Comment by damianooldoni** [comment]
As for issue #65 , I did a first draft in https://trias-project.github.io/indicators/occurrence_indicators_appearing_taxa.html of the new site.

**Comment by damianooldoni** [comment]
how to merge this table with rersults ot #65? But should be merged?

**Comment by timadriaens** [comment]
species alien to one Belgian region (see [this issue](https://github.com/trias-project/unified-checklist/issues/49)) should be excluded
