### ISSUE TITLE
Get info about alien species at protect area level

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/indicators#73]
Requeste of @timadriaens: add analysis at protected area level.
A tabular file as output:

protected_area_id | type | year | taxonKey | obs | ncells | coverage 
--- | --- | --- | --- | --- | --- | ---
BE3748432 | A | 2010 | 124245 | 34 | 15 | 0.30
BE3748432 | A | 2011 | 124245 | 44 | 29 | 0.58
BE3748432 | A | 2012 | 124245 | 58 | 32 | 0.64
BE3748432 | A | 2013 | 124245 | 69 | 36 | 0.72
BE3748432 | A | 2014 | 124245 | 88 | 43 | 0.86
BE3748432 | A | 2015 | 124245 | 92 | 45 | 0.90
BE3748432 | A | 2016 | 124245 | 95 | 47 | 0.94
BE3748432 | A | 2017 | 124245 | 99 | 48 | 0.96

**Comment by timadriaens** [comment]
great! Can you add common and scientific names please?

**Comment by peterdesmet** [comment]
Scientific names (and maybe common names: harder) should be added via an extra metadata file

**Comment by timadriaens** [comment]
For analysis purposes, we would also need the native species, so it would be good to add taxon information and 

protected_area_id | type | year | taxonKey | obs | ncells | coverage  | Unified (alien/native) | Kingdom |
--- | --- | --- | --- | --- | --- | --- | --- | --- |
BE3748432 | A | 2010 | 124245 | 34 | 15 | 0.30 | alien | plantae |
BE3748432 | A | 2011 | 124245 | 44 | 29 | 0.58 | native | animalia |
BE3748432 | A | 2012 | 124245 | 58 | 32 | 0.64 | native | plantae |
BE3748432 | A | 2013 | 124245 | 69 | 36 | 0.72 | alien | plantae |
BE3748432 | A | 2014 | 124245 | 88 | 43 | 0.86 | native | plantae |
BE3748432 | A | 2015 | 124245 | 92 | 45 | 0.90 | alien | animalia |
BE3748432 | A | 2016 | 124245 | 95 | 47 | 0.94 | alien | animalia |
BE3748432 | A | 2017 | 124245 | 99 | 48 | 0.96 | native | plantae |

**Comment by timadriaens** [comment]
Let me know when you want to write metadata together for zenodo publication @damianooldoni

**Comment by damianooldoni** [comment]
Thanks @timadriaens and @peterdesmet for your suggestions.

I will produce three files: 
- the cube at protected area level
- the taxonomic metadata file
- the protected area metadata file

### Cube at protected area level

protected_area_id | type | year | taxonKey | n | ncells | coverage | min_coord_uncertainty
--- | --- | --- | --- | --- | --- | --- | --- | 
BE3748432 | A | 2010 | 124245 | 34 | 15 | 0.30 | 100
BE3748432 | A | 2011 | 124245 | 44 | 29 | 0.58 | 230
BE3748432 | A | 2012 | 124245 | 58 | 32 | 0.64 | 3400
BE3748432 | A | 2013 | 124245 | 69 | 36 | 0.72 | 10000
BE3748432 | A | 2014 | 124245 | 88 | 43 | 0.86 | 100
BE3748432 | A | 2015 | 124245 | 92 | 45 | 0.90 | 100
BE3748432 | A | 2016 | 124245 | 95 | 47 | 0.94 | 10
BE3748432 | A | 2017 | 124245 | 99 | 48 | 0.96 | 10

### Taxonomic metadata file

taxonKey | scientificName | rank |  kingdom | phylum | class | taxonomicStatus | includes |
--- | --- | --- | --- | --- | --- | --- | ---
124245 | Damianus damianis (Oldoni, 1982) | SPECIES | Animalia | Chordata | Mammalia | DOUBTFUL | "124245: Damianus damianis (Adriaens, 1982) \| 124246: Damianus damianis adriaensis (Oldoni, 2020)"

### Protected metadata file

protected_area_id | type_legend | area_name
--- | --- | ---
BE3748432 | Bird's Directive | Het Zwin

**Comment by damianooldoni** [comment]
As mentioned in PR @77, I worked on this and I produced a pipeline https://trias-project.github.io/indicators/occurrence_species_protected_areas_level.html in chapter Appendix of indicators webpage.

About the finale table and the two related metadata, the table is too big to be put on GitHub. Indeed, we could publish it on Zenodo. Meanwhile, the output files are tab separated and are downloadable via this [Firefox Send link](https://send.firefox.com/download/a521f2e05779dbe5/#HvGtNgfRygX6TE5QwzQqiQ).

@timadriaens :  feel free to start a draft about metadata. I will on Tuesday start a Zenodo upload and invite you to join for improvement. @peterdesmet: I learned a lot while publishing with you the cubes, still your review of this new TrIAS Zenodo publication is welcome :smile:

**Comment by peterdesmet** [comment]
@damianooldoni ok, ping when I should review

**Comment by damianooldoni** [comment]
I started an upload to Zenodo. Link: https://zenodo.org/deposit/3784227.
@timadriaens : can you check metadata? You can login by using my INBO email and the password I will send you privately.

**Comment by damianooldoni** [comment]
Thanks @timadriaens to further work on metadata.
Please, be aware that zenodo writing interface is not like GitHub, so if you want to add `code` you need to do write in Broncode modus. See screenshot here below:
![image](https://user-images.githubusercontent.com/33662631/81202089-5e808900-8fc6-11ea-91ab-a0016381057e.png)

So, please refresh your upload page to see my change.

**Comment by damianooldoni** [comment]
After video discussion with @timadriaens , we agreed to modify the protected area data.frame by adding AOO (Area Of Occupancy) and coverage of **infraspecific alien taxa**. This means that the analysis is not anymore at species level but ensures a better analysis of trends of alien species.

Example here below where the second line will be added:


ITECODE | SITETYPE | year | speciesKey | n | aoo | coverage | min_coord_uncertainty | is_alien | remarks
--- | --- | --- | --- | --- | --- | --- | --- | --- | ---
BE2200031 | B | 1998 | 2889011 | 8 | 5 | 0.06 | 700 | FALSE | Infraspecific alien taxa present. 7901010:Rumex obtusifolius subsp. sylvestris (Lam.) Celak.
BE2200031 | B | 1998 | 7901010 | 6 | 4 | 0.048 | 1000 | TRUE | 

How to do it? By using not only the Belgian occurrence cube at species level, but also the occurrence cube of alien taxa based on the unified (as output of https://github.com/trias-project/occ-cube-alien and published on Zenodo).

**Comment by damianooldoni** [comment]
Infraspecific taxa have been added to protected area analysis.
@timadriaens : e.g. check again the spreading data of alien taxa in Flemish habitat directive areas, https://github.com/trias-project/indicators/blob/master/data/output/protected_areas_analysis/n_prot_areas_per_species_flanders_habitat.csv. 
Trachemys scripta elegans is present in 37 areas, Trachemys scripta troostii in 32 areas while Trachemys scripta scripta in 28.

**Comment by timadriaens** [comment]
ok thx

**Comment by damianooldoni** [comment]
@peterdesmet: it's time to ping you for a review of the zenodo upload: https://zenodo.org/deposit/3784227#.

You know the credentials.

**Comment by peterdesmet** [comment]
Done!

**Comment by damianooldoni** [comment]
Dataset published on zenodo :partying_face:  
https://zenodo.org/record/3784227
