### ISSUE TITLE
Review taxon keys of EU concern species list

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/indicators#96]
After the fast PR #95 for replacing the synonym _Orocnetes virilis_ with the accepted Faxonius virilis, I checked the GBIF taxon keys of all species in [eu_concern_species.tsv](https://github.com/trias-project/indicators/blob/master/data/input/eu_concern_species.tsv). I found some outdated keys. Here below a table with my proposal for updates:

- [Pennisetum setaceum](https://www.gbif.org/species/2706134) is a **synonym**. To be replaced by accepted [Cenchrus setaceus](https://www.gbif.org/species/5828232)
- [Pueraria lobata](https://www.gbif.org/species/9035634) deleted on March, 3 2021. This other [Pueraria lobata](https://www.gbif.org/species/2977654) (Pueraria lobata (Willd.) Ohwi) is synonym of the variety Pueraria montana var. lobata (https://www.gbif.org/species/2977647). Based on English common name and distribution, I suggest to use the species [Pueraria montana](https://www.gbif.org/species/2977636)
- [Herpestes javanicus](https://www.gbif.org/species/8858565) has been deleted on Feb 1, 2018. To be replaced by this [Herpestes javanicus](https://www.gbif.org/species/2434271) (_Herpestes javanicus (É.Geoffroy Saint-Hilaire, 1818)_)
- [Orconectes limosus](https://www.gbif.org/species/2227000) is a synonym, to be replaced by accepted [Faxonius limosus](https://www.gbif.org/species/8909595)
- [Cardiospermum grandiflorum](https://www.gbif.org/species/9685025) to be replaced by this [Cardiospermum grandiflorum](https://www.gbif.org/species/3189935)
- [Acacia saligna Willd.](https://www.gbif.org/species/8790482) has been deleted on March 3, 2021. To be replaced by this [Acacia saligna](https://www.gbif.org/species/2978552)
- [Ehrharta calycina](https://www.gbif.org/species/7644403) is a synonym of [Ehrharta melicoides](https://www.gbif.org/species/4116661). Based on number of occurrences and the English common name, I think we should point to this [Ehrharta calycina](https://www.gbif.org/species/2702865) (_Ehrharta calycina Sm._)

**Comment by timadriaens** [comment]
Thanks for checking @damianooldoni! Synonyms are now also mentioned in the [consolidated implementing act](https://ec.europa.eu/environment/nature/invasivealien/docs/R_2016_1141_Union-list-2019-consolidation.pdf) of the EU Regulation which represents the legal reference for the taxonomy of the Union List IAS.

These look very much OK with me and in line with the implementing act:

- Herpestes javanicus: OK
- Faxonius limosus: OK
- Cardiospermum: OK (authority should be Sw. indeed)
- Acacia saligna: OK (Acacia cyanophylla Lindl. is commonly used synonym - in line with the implementing act)
- Ehrharta calycina: OK with the proposal, the species we need is indeed Ehrharta calycina Sm. (in line with the implementing act)

For these I have doubts and would need to consult plant or Regulation people:

- Pennisetum to Cenchrus: yes, it changed to cenchrus, but as the legal text (see below) mentions _Pennisetum setaceum (Forssk.) Chiov._ I would perhaps stick to Pennisetum for now. Question: how is it possible that Cenchrus has more occurrences on gbif considering they should be synonymous? I can raise the issue for clarification within the EU network. For data extraction, don't we need to select both keys then?
- Pueraria lobata: the implementing act mentions "_Pueraria montana (Lour.) Merr. var. lobata (Willd.) (Pueraria lobata (Willd.)
Ohwi)_". Again, here, for data extraction there are differences in the number of occurrences so I wonder if data from both GBIF keys should then be selected? In fact, there is something strange here for kudzu vine. The original EPPO pest risk assessments used for listing mentions 2 different names: Pueraria lobata (Kirk) Cockayne and Pueraria montana (Lour.) Merr.

**Comment by timadriaens** [comment]
I fact I am starting to totally wonder if we should ask the Commission whether they want to consider gbif keys on top of the taxonomy in the technical support contract of IUCN. The thing is that we know also EASIN has to deal with harvesting data from GBIF (and they too have had issues with wrongly assigned GBIF keys in the past).

**Comment by damianooldoni** [comment]
Good point, @timadriaens! I think the more institutions at each level deal with GBIF Backbone, the faster taxonomy issues will be solved.

About [Pennisetum setaceum (Forssk.) Chiov.](https://www.gbif.org/species/2706134) and the accepted [Cenchrus setaceus (Forssk.) Morrone](https://www.gbif.org/species/5828232), your question has an easy answer: the number of occurrences you see on the GBIF webpages are the ones related to the specific taxonKey: they don't take into account synonym relation. But in TrIAS indicators we first get ALL occurrences in Belgium to make the cube and while grouping, we group by acceptedKey. In this way we get all occurrences from the accepted and all its synonyms.

To better understand this, it's easier to check this in the API page for these two species:
the synonym Pennisetum setaceum (Forssk.) Chiov. https://api.gbif.org/v1/species/2706134 has a non empty field `acceptedKey`, 5828232, which is the taxonKey of Cenchrus setaceus (Forssk.) Morrone: https://api.gbif.org/v1/species/5828232
In this way I can aggregate data from all synonyms of the same accepted species.


Said this, the same applies to [_Pueraria lobata (Willd.) Ohwi_](https://www.gbif.org/species/2977654), a species synonym of the variety [_Pueraria montana var. lobata (Willd.) Maesen & S.M.Almeida ex Sanjappa & Predeep_](https://www.gbif.org/species/2977647): while retrieving the data for indicators, we aggregate all data from all synonyms and corresponding accepted.

So, the **two rules** for updating the list of EU concern species list are:
1. insert the accepted taxon if you trust it
2. insert the synonym (as such) if you don't trust it

@timadriaens: if you prefer, we could add a `comment` column to the list if you want to trace better how we got to add X instead of Y or why we changed X with Y.

**Comment by timadriaens** [comment]
OK, clear on the synonym issue, I knew we handled them intelligently in the TrIAS package! Which brings us to the gbif interface which does not allow to visualize occurrences from multiple taxa at once (right ?) - it would be a nice idea for future development imo, it would make comparison of such related taxa or synonyms much more easy to a user.

So on Pueraria and Cenchrus: I do trust the accepted.

Yes, I think adding a field with our 'justification' would be a good idea for traceability.

**Comment by damianooldoni** [comment]
Obsolete: we published the EU concern species list on GBIF and maintaining it there.
